### PR TITLE
Date parsing fix

### LINKED ISSUE #2: Not updating config in App Store builds
On App Store builds, I'm seeing echo changes not reflected in my app. I'm going to be fixing the issue but I want to document things and maybe get some help from the OSS community.

Aerodramus first [does a HEAD request](https://github.com/artsy/Aerodramus/blob/7c954b342b599cd7881fca5d71047d109c21a4ba/Pod/Classes/AeroRouter.m#L26-L34) and [checks the `Updated-At` header](https://github.com/artsy/Aerodramus/blob/7c954b342b599cd7881fca5d71047d109c21a4ba/Pod/Classes/Aerodramus.m#L82-L107) of the response to determine if there's new echo config that needs to be fetched and parsed. So that check must be failing, and I'm only seeing if fail on App Store builds.

The way that Aerodramus fetches network requests [relies on the default session config](https://github.com/artsy/Aerodramus/blob/7c954b342b599cd7881fca5d71047d109c21a4ba/Pod/Classes/Aerodramus.m#L154-L160), which mentions "on-disk caching" in its documentation. My guess is that that's the culprit. We should disable the caching in any case. If anyone can verify, I'd be very grateful :bow:

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #2.

### CODE REVIEW

**Comment by alloy** [comment]
So this doesn’t really change anything but fallback to assuming it should update if date parsing fails, or did something change in Aerodramus itself?

**Comment by alloy** [comment]
Oh wait, this is the Aerodramus repo :D

**Comment by alloy** [comment]
Ok, so, I’m fine with this change and have a fallback in principle, but I wouldn’t want us to not fix the actual issue, fail parsing all the time, and download new config all the time.

**Comment by ashfurrow** [comment]
Totally, I added more logging to find out what exactly is failing to parse for that reason. In the mean time, auctions relies on Echo/Aerodramus for critical functionality, and I'd much rather risk unnecessary updates than fail to update altogether.

**Comment by alloy** [comment]
Gotcha, makes sense 👍

**Comment by orta** [comment]
👍

**Pull request merged**
